# Air configuration for hot-reload

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
# Build your app to ./tmp/main, then run it with args below.
cmd  = "go build -o ./tmp/main ."
bin  = "./tmp/main"
args_bin = ["serve-rest"]        # <- your run arg
delay = 1000

# Watch/ignore settings
include_ext  = ["go", "mod", "sum", "tpl", "tmpl", "html"]
exclude_dir  = ["assets", "tmp", "vendor", "testdata", "logs", ".git", "proto"]
exclude_file = []
exclude_regex = ["_test.go"]

# Logging, colors, screen
log = "build-errors.log"

[color]
build  = "yellow"
main   = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
